                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                let pass = prompt('Password:');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (pass === 'Jesus' || pass === 'jesus') {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const ht = document.querySelector(`.verga`)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ht.innerText= pass + ' ' +'è un idiota';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    while (true) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        console.log(pass + ' ' +'è un idiota');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    alert('password incorrecto')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }



